version: '3.7'

services:
  hauser-php8:
    image: hauser-php8:dev
    container_name: hauser-php8
    build:
      context: ./docker
      target: hauser-php8
      dockerfile: ./Dockerfile.dev
    ports:
      - "82:80" 
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/apache.ports.conf:/etc/apache2/ports.conf
      - ./docker/apache.vhost.conf:/etc/apache2/sites-enabled/vhost.conf
  mysqldb:
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/database:/var/lib/mysql
      - ./docker/mysql/mariadb.cnf:/etc/mysql/mariadb.cnf

  adminer:
    image: adminer
    ports:
      - 83:8080
